name: finance_app
description: HUMO Card expense tracker — парсинг сообщений Telegram бота

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.1
  equatable: ^2.0.5

  # Local database
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # Formatting (dates, numbers, ru locale)
  intl: ^0.19.0

  # Color picker
  flutter_colorpicker: ^1.1.0

  # UUID generation
  uuid: ^4.4.0

  # DIO requests
  dio: ^5.9.2

  # Secure storage for tokens
  flutter_secure_storage: ^9.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/